baseURL = 'https://bulbak1.github.io/Project-practice-2025/site/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "ananke"

[[menu.main]]
  name = "О проекте"
  url = "/about/"
  weight = 1

[[menu.main]]
  name = "Участники"
  url = "/team/"
  weight = 2

[[menu.main]]
  name = "Журнал"
  url = "/posts/"
  weight = 3

[[menu.main]]
  name = "Ресурсы"
  url = "/resources/"
  weight = 4